# Generated by Django 4.1.6 on 2023-02-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('None', 'None'), ('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Legs', 'Legs'), ('Abs', 'Abs')], default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
                ('rep_number', models.IntegerField()),
                ('exertion_level', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('exercise_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs_ex.exercise_category')),
            ],
        ),
    ]
