# Generated by Django 4.1.6 on 2023-02-13 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs_ex', '0002_rename_rep_number_exercise_set_number_of_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_set',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
